name: Test GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Print environment information
        run: |
          echo "Running on: ${{ runner.os }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: Test step
        run: echo "GitHub Actions is working! 🎉"
